////////////////////////////////////
// Priyokti Rana
// hw06
// Roulette
// October 13, 2014
// CSE02 with Professor Brain Chen
// This program prompts the user to enter a number and through a series of loops, calculates how many times this number leads to a win and loss in a game of roulette.

//importing scanner
import java.util.Scanner;

//statement needed for generate random boolean values
import java.util.Random;

// define a class
public class Roulette {
    
// add main methods
    public static void main(String [] args) {
        
    Scanner myScanner; //declaring scanner as variable
    
    myScanner = new Scanner ( System.in ); //statement calling the scanner constructor
    
    System.out.println("Please enter a number between 1 and 38.");
    int mynumber = myScanner.nextInt(); //prompting user to enter their bet
    
    int totalsim=1; //variable for total number of simulations
    int allmywinnings=0; //total number of wins
    int losses=0; //total number of losses
    int profit=0; //total profit
    
    if ((mynumber>38)||(mynumber<1)){ //checking whether the number is in the range
        System.out.println("The number you entered is not between 1 and 38.");
    }
    
    else{ //runs if number is within range
        while (totalsim <=1000){ //runs total of 1000 times (as a whole)
            
            int randomnum = (int)(Math.random() * 38); //the random number generated by the program
            int winnings = 0; // declaring variable for number of times the p
            int numberofrolls = 1; //comes back to this number after every loop
            
        while(numberofrolls <=100){ //runs a total of 100 times
            
            if(mynumber==randomnum){ //if number user entered is equal to number generated
            winnings++; //number of times won is added
            allmywinnings++; //number of total winnings (does not reset like "winnings")
        } //end of if statement
        
        numberofrolls++; //makes loop repeat until it reaches 100
        }//end of while loop
        
            if(winnings==0){ //if there are no wins, then a loss is added
                losses++; //added every time numbers do not match
            } //end of if statement
                
                else if(winnings>=3){ //need to do this in order to calculate total profit
            profit++; //added for every win (after the third)
        } //end of else if statement
        
        totalsim++;// makes program keep running until 1000th run
        }//end of while
        
    }//end of else statement
        
                //statements showing what happened in the bet        
                System.out.println("You lost " + losses + " times.");
                System.out.println("You won $ " + (allmywinnings*36));
                System.out.println("You made a profit " +profit+" times.");
    
        
        
       
} //end main
    
} //end  class